### PR TITLE
Add '-i' dmenu flag to accept searches from small letter

### PR DESCRIPTION
**Pull request by wzykubek**
+add required deps to README.md

### CODE REVIEW

**Comment by cdown** [comment]
Huh? If you want `-i`, you can just pass it to mpdmenu as in the readme, no?

**Comment by wzykubek** [comment]
No, it doesn't work.
`-i` is IMO very usefull, and should be enabled every time.

**Comment by cdown** [comment]
Since I use `-i` every single day without issue, I'm quite certain it works ;-)

https://github.com/cdown/dwm/blob/938e92b109420cb9d993bc24d377aba87efe53df/config.h#L84-L85

I'm not going to set `-i` globally because there's no way for people to opt out if they don't like the behaviour.

Also, `-h` isn't a valid option to dmenu (https://git.suckless.org/dmenu/file/dmenu.c.html#l737), did you really test this?

**Comment by wzykubek** [comment]
I tested it and it didn't worked for me but never mind, I forked your repo and it's okay, but I tought that `-i` option is usefull for anyone.

And `-h` has been a typo, sorry.

**Comment by cdown** [comment]
Sure thing. I'm going to close this, then. :-)

**Pull request closed without merging**
